### ISSUE TITLE
Please allow track-based download control

### ISSUE THREAD

**Issue by zypA13510** [jaymoulin/bandcamp-down-chrome-ext#8]
On many occasions, this extension will fail on one of the tracks in an album but lacks timeout mechanism. It will wait forever for the download to complete (a notification will appear saying the download of the track failed, but nothing changes. Status on the download list is still "waiting" and no zip file will be created in the downloads folder). The only way to resolve this seems to be restarting the entire browser for the extension to reset, which is very inconvenient. Please consider adding some basic control to the downloads i.e. pause/resume, cancel/retry etc..

**Comment by jaymoulin** [comment]
Since #9 is fixed, this shouldn't bother you anymore. pause/start is a bit difficult to implement without a real gain. Cancel and retry were already added in 0.3.0

**Comment by farazfp** [comment]
The issue persists in many cases where timeout occurs and say, a single track remains to be downloaded. The only cure seems to be to reload the main album page and request a full download again, which apparently discards whatever has already been downloaded. I am not seeing cancel or retry buttons in the options page also. Even if pause/start is difficult, a stop/restart button for each track could be very useful. Thanks!

**Comment by jaymoulin** [comment]
@farazfp Please create another issue for considering cancel button on pending request. 
Also be sure you use KeepTune (https://chrome.google.com/webstore/detail/keeptune/oidamlgjlcjhdpkflfefcemhmfpmlfbj) to see this update if/when this new feature request is handled.
